#!/bin/bash

dnf update -y
systemctl disable firewalld || true
systemctl stop firewalld || true
dnf install -y docker-distribution
systemctl start docker-distribution
systemctl enable docker-distribution
systemctl is-active docker-distribution
